import type { Metadata } from "next";
import { Advent_Pro } from "next/font/google";
import "./globals.css";
import AdSense from "@/components/AdSense";

const advent = Advent_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Na Lata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <AdSense pId={process.env.GOOGLE_DATA_AD!} />
      </head>
      <body
        className={`${advent.className} antialiased bg-background-100 flex justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
